@startuml exercice1

right to left direction

actor Etudiant as E

rectangle "Espace Personnel"{
    usecase "Créer un compte" as UC1
    usecase "Se connecter" as UC2
    usecase "Vérifier identifiants" as UC3
    usecase "Se déconnecter" as UC4
}

E -> UC1
E -> UC2
E -> UC4

UC3 ..> UC2:include
UC4 ..> UC2:required


@enduml